server:
  port: 8080
  servlet:
    context-path: /nacos
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: nacos-tutorials
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        namespace: java-turtorials-point
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        namespace: ${spring.cloud.nacos.discovery.namespace}
        extension-configs:
          - data-id: nacos-datatype.yml
            group: DEFAULT_GROUP
            refresh: true